spring.application.nome=cose-di-casa

spring.main.allow-bean-definition-overriding=true

spring.datasource.url=jdbc:postgresql://app-casa-db:5432/app_casa_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
